//! Tiny YAML-frontmatter parser tailored to the demo seed format.
//!
//! Recognises a leading block delimited by lines containing only `---` and
//! a trailing block of the same shape. Inside, each line is `key: "quoted
//! value"` (unquoted values are also accepted). This is intentionally far
//! short of a full YAML parser — the seed input is generated by us, so the
//! constrained format is fine.

use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Article {
    pub frontmatter: Frontmatter,
    pub body: String,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Frontmatter {
    pub title: String,
    pub author_name: Option<String>,
    pub author_url: Option<String>,
    pub created_at: Option<String>,
    pub state: Option<String>,
    pub tombstone_reason: Option<String>,
    pub redaction_reason: Option<String>,
}

impl Frontmatter {
    fn from_map(map: HashMap<String, String>) -> Self {
        let take = |k: &str| map.get(k).cloned();
        Self {
            title: take("title").unwrap_or_default(),
            author_name: take("author_name"),
            author_url: take("author_url"),
            created_at: take("created_at"),
            state: take("state"),
            tombstone_reason: take("tombstone_reason"),
            redaction_reason: take("redaction_reason"),
        }
    }
}

pub fn parse_article(input: &str) -> Article {
    // Look for the leading `---\n`.
    let rest = match input.strip_prefix("---\n") {
        Some(r) => r,
        None => {
            return Article {
                frontmatter: Frontmatter::default(),
                body: input.to_owned(),
            };
        }
    };
    // Find the closing `---` line.
    let close = match rest.find("\n---") {
        Some(i) => i,
        None => {
            return Article {
                frontmatter: Frontmatter::default(),
                body: rest.to_owned(),
            };
        }
    };
    let fm_block = &rest[..close];
    // Body starts after the `---` line.
    let body_start = close + "\n---".len();
    let body = rest[body_start..].trim_start_matches('\n').to_owned();

    let mut map: HashMap<String, String> = HashMap::new();
    for line in fm_block.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let (k, v) = match line.split_once(':') {
            Some((k, v)) => (k.trim(), v.trim()),
            None => continue,
        };
        let v = strip_quotes(v);
        map.insert(k.to_owned(), v);
    }

    Article {
        frontmatter: Frontmatter::from_map(map),
        body,
    }
}

fn strip_quotes(v: &str) -> String {
    let v = v.trim();
    if (v.starts_with('"') && v.ends_with('"') && v.len() >= 2)
        || (v.starts_with('\'') && v.ends_with('\'') && v.len() >= 2)
    {
        v[1..v.len() - 1].replace("\\\"", "\"")
    } else {
        v.to_owned()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_minimal_article() {
        // Arrange
        let input = "---\ntitle: \"Hello\"\nstate: \"live\"\n---\n\nBody text.\n";

        // Act
        let art = parse_article(input);

        // Assert
        assert_eq!(art.frontmatter.title, "Hello");
        assert_eq!(art.frontmatter.state.as_deref(), Some("live"));
        assert_eq!(art.body.trim(), "Body text.");
    }

    #[test]
    fn parses_all_optional_fields() {
        // Arrange
        let input = "---\ntitle: \"X\"\nauthor_name: \"A\"\nauthor_url: \"https://example.com\"\ncreated_at: \"2026-04-30T00:00:00Z\"\nstate: \"tombstone\"\ntombstone_reason: \"r\"\n---\nBody\n";

        // Act
        let art = parse_article(input);

        // Assert
        assert_eq!(art.frontmatter.author_name.as_deref(), Some("A"));
        assert_eq!(
            art.frontmatter.author_url.as_deref(),
            Some("https://example.com")
        );
        assert_eq!(
            art.frontmatter.created_at.as_deref(),
            Some("2026-04-30T00:00:00Z")
        );
        assert_eq!(art.frontmatter.state.as_deref(), Some("tombstone"));
        assert_eq!(art.frontmatter.tombstone_reason.as_deref(), Some("r"));
    }

    #[test]
    fn no_frontmatter_keeps_full_body() {
        // Arrange
        let input = "Plain markdown body, no frontmatter.\n";

        // Act
        let art = parse_article(input);

        // Assert
        assert_eq!(art.frontmatter.title, "");
        assert_eq!(art.body, input);
    }
}
