// `headlines-proto` exposes the generated `headlines.v1` Rust types plus the
// authorization table that the proto-driven `AuthorizationLayer` consults.
//
// The build script (`build.rs`) compiles every `headlines/v1/*.proto` via
// `tonic-build`, emits the descriptor set to `$OUT_DIR/descriptor.bin`, and
// projects every method's `auth_requirement` MethodOption into a phf map at
// `$OUT_DIR/auth_table.rs`. The build FAILS if any RPC is missing the option.

#![allow(clippy::all)]
#![allow(missing_docs)]
#![allow(rustdoc::broken_intra_doc_links)]

pub mod v1 {
    //! Generated `headlines.v1` types (messages, enums, service stubs).
    tonic::include_proto!("headlines.v1");
}

pub use headlines_core::SubjectClass;

/// Authorization specification attached to one RPC by its proto
/// `auth_requirement` MethodOption.
///
/// Field semantics mirror `headlines.v1.AuthRequirement`:
///   - `allowed`: subject classes that may invoke the RPC.
///   - `scopes`: scope strings that gate the `System` subject class. Empty
///      slice means "any System subject is acceptable" — meaningful only when
///      `allowed` includes `SubjectClass::System`.
#[derive(Debug, Clone, Copy)]
pub struct AuthSpec {
    pub allowed: &'static [SubjectClass],
    pub scopes: &'static [&'static str],
}

// `AUTH_TABLE` is generated by `build.rs` from the FileDescriptorSet and is a
// `phf::Map<&'static str, AuthSpec>` keyed by full RPC method name
// (e.g. `"/headlines.v1.AccountService/CreateAccount"`).
include!(concat!(env!("OUT_DIR"), "/auth_table.rs"));
