//! `PgEventRepo` — Diesel-async impl of `headlines_core::repo::EventRepo`.
//!
//! Per `docs/design/events.md`:
//!
//! - `record`: single insert — `id` (UUIDv7) is generated by the service
//!   handler, `received_at` is set server-side by Postgres `now()`.
//! - `record_batch`: single tx — all rows inserted via one
//!   `INSERT ... VALUES (...), (...), ...` so the batch is all-or-none. The
//!   service handler validates everything first; this layer trusts the input.
//! - `list`: keyset cursor on `(received_at, id) ASC`. Filters
//!   (`user_id`, `article_id`, `types`, `received_after`, `received_before`)
//!   are AND-combined and pushed into the SQL.
//!
//! `properties` is stored as `jsonb`; the service layer is responsible for the
//! type-specific JSON shape (see `docs/design/events.md` § Storage). The repo
//! treats it as opaque bytes-on-the-wire and never inspects the content.
//!
//! Like `feed_recommendation` / `account_stream`, the `list` SQL is
//! `diesel::sql_query` rather than the typed DSL — the dynamic-filter shape
//! plus the `(received_at, id)` keyset is awkward to write in the typed DSL,
//! and the SQL maps 1-to-1 to the spec.

use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD as B64URL;
use chrono::{DateTime, Utc};
use diesel::prelude::*;
use diesel::sql_types::{Nullable, Text, Timestamptz, Uuid as SqlUuid};
use diesel_async::RunQueryDsl;
use serde_json::Value as Json;
use uuid::Uuid;

use headlines_core::HeadlinesError;
use headlines_core::repo::PageToken;
use headlines_core::repo::events::{
    Event, EventRecord, EventRepo, EventType, ListEventsFilter, ListEventsPage,
};

use crate::Db;
use crate::schema::events;

/// Concrete `EventRepo` over the `Db` pool.
#[derive(Clone)]
pub struct PgEventRepo {
    db: Db,
}

impl PgEventRepo {
    pub fn new(db: Db) -> Self {
        Self { db }
    }
}

// ---------------------------------------------------------------------------
// Diesel insert / row shapes.
// ---------------------------------------------------------------------------

/// Insertable row for `events`. `received_at` is set by the DB (`DEFAULT now()`
/// is not on the column, so we explicitly bind `now()` via `Utc::now()` from
/// the caller's perspective; the test harness on the integration side accepts
/// either as long as ordering holds).
#[derive(Insertable)]
#[diesel(table_name = events)]
struct InsertEvent<'a> {
    id: Uuid,
    user_id: Uuid,
    article_id: Option<Uuid>,
    #[diesel(column_name = type_)]
    type_: &'a str,
    occurred_at: DateTime<Utc>,
    received_at: DateTime<Utc>,
    surface: &'a str,
    properties: &'a Json,
}

/// Row read back from `events`.
#[derive(Debug, Clone, Queryable, QueryableByName)]
#[diesel(table_name = events)]
struct EventRow {
    #[diesel(sql_type = SqlUuid)]
    id: Uuid,
    #[diesel(sql_type = SqlUuid)]
    user_id: Uuid,
    #[diesel(sql_type = Nullable<SqlUuid>)]
    article_id: Option<Uuid>,
    #[diesel(sql_type = Text, column_name = type_)]
    type_: String,
    #[diesel(sql_type = Timestamptz)]
    occurred_at: DateTime<Utc>,
    #[diesel(sql_type = Timestamptz)]
    received_at: DateTime<Utc>,
    #[diesel(sql_type = Text)]
    surface: String,
    #[diesel(sql_type = diesel::sql_types::Jsonb)]
    properties: Json,
}

impl From<EventRow> for Event {
    fn from(r: EventRow) -> Self {
        Event {
            id: r.id,
            user_id: r.user_id,
            article_id: r.article_id,
            r#type: EventType(r.type_),
            occurred_at: r.occurred_at,
            received_at: r.received_at,
            surface: r.surface,
            properties: r.properties,
        }
    }
}

// ---------------------------------------------------------------------------
// Cursor codec — keyset on (received_at, id) ASC.
// ---------------------------------------------------------------------------

const DEFAULT_PAGE_SIZE: i32 = 50;
const MIN_PAGE_SIZE: i32 = 1;
const MAX_PAGE_SIZE: i32 = 200;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct PageCursor {
    /// RFC3339 of the last row's `received_at`.
    r: String,
    /// Last row's `id`.
    i: Uuid,
}

fn encode_cursor(received_at: &DateTime<Utc>, id: Uuid) -> PageToken {
    let cursor = PageCursor {
        r: received_at.to_rfc3339(),
        i: id,
    };
    let json = serde_json::to_vec(&cursor).expect("PageCursor is always serializable");
    PageToken(B64URL.encode(json))
}

fn decode_cursor(raw: &str) -> Result<(DateTime<Utc>, Uuid), HeadlinesError> {
    let bytes = B64URL
        .decode(raw)
        .map_err(|e| HeadlinesError::InvalidCursor {
            reason: format!("base64: {e}"),
        })?;
    let pc: PageCursor =
        serde_json::from_slice(&bytes).map_err(|e| HeadlinesError::InvalidCursor {
            reason: format!("json: {e}"),
        })?;
    let dt = DateTime::parse_from_rfc3339(&pc.r)
        .map_err(|e| HeadlinesError::InvalidCursor {
            reason: format!("rfc3339: {e}"),
        })?
        .with_timezone(&Utc);
    Ok((dt, pc.i))
}

fn clamp_page_size(raw: i32) -> i32 {
    if raw <= 0 {
        DEFAULT_PAGE_SIZE
    } else {
        raw.clamp(MIN_PAGE_SIZE, MAX_PAGE_SIZE)
    }
}

// ---------------------------------------------------------------------------
// EventRepo impl
// ---------------------------------------------------------------------------

/// Allocate a fresh server-side identity + receive timestamp for each record.
/// `id` UUIDv7 is generated by the service handler before the call; this
/// helper is used only by `record_batch` where the repo signature passes the
/// `EventRecord` (no pre-minted id) but we still want a clean separation.
fn new_id_and_now() -> (Uuid, DateTime<Utc>) {
    (Uuid::now_v7(), Utc::now())
}

impl EventRepo for PgEventRepo {
    async fn record(&self, record: EventRecord) -> Result<Event, HeadlinesError> {
        let mut conn = self.db.get().await.map_err(HeadlinesError::Internal)?;
        let (id, received_at) = new_id_and_now();
        let insert = InsertEvent {
            id,
            user_id: record.user_id,
            article_id: record.article_id,
            type_: &record.r#type.0,
            occurred_at: record.occurred_at,
            received_at,
            surface: &record.surface,
            properties: &record.properties,
        };
        let row: EventRow = diesel::insert_into(events::table)
            .values(&insert)
            .returning((
                events::id,
                events::user_id,
                events::article_id,
                events::type_,
                events::occurred_at,
                events::received_at,
                events::surface,
                events::properties,
            ))
            .get_result(&mut conn)
            .await
            .map_err(|e| HeadlinesError::Internal(anyhow::anyhow!("insert event: {e}")))?;
        Ok(row.into())
    }

    async fn record_batch(&self, records: Vec<EventRecord>) -> Result<Vec<Event>, HeadlinesError> {
        if records.is_empty() {
            return Ok(Vec::new());
        }
        let mut conn = self.db.get().await.map_err(HeadlinesError::Internal)?;

        // Generate ids + received_at for every record up front. Putting them
        // in a single multi-row INSERT inside one tx delivers the
        // all-or-none semantics required by `events.md`. Diesel's
        // `insert_into(...).values(&Vec<Insertable>)` already issues one
        // statement; combined with deadpool's per-call connection it's
        // implicitly transactional at the statement level for a single
        // INSERT (PostgreSQL guarantees atomicity of a single statement).
        let now = Utc::now();
        let mut ids: Vec<Uuid> = Vec::with_capacity(records.len());
        for _ in 0..records.len() {
            ids.push(Uuid::now_v7());
        }

        let inserts: Vec<InsertEvent> = records
            .iter()
            .zip(ids.iter())
            .map(|(r, id)| InsertEvent {
                id: *id,
                user_id: r.user_id,
                article_id: r.article_id,
                type_: &r.r#type.0,
                occurred_at: r.occurred_at,
                received_at: now,
                surface: &r.surface,
                properties: &r.properties,
            })
            .collect();

        let rows: Vec<EventRow> = diesel::insert_into(events::table)
            .values(&inserts)
            .returning((
                events::id,
                events::user_id,
                events::article_id,
                events::type_,
                events::occurred_at,
                events::received_at,
                events::surface,
                events::properties,
            ))
            .get_results(&mut conn)
            .await
            .map_err(|e| HeadlinesError::Internal(anyhow::anyhow!("insert event batch: {e}")))?;

        // Postgres preserves VALUES order in a single multi-row INSERT, so
        // the returned rows align with `records`. We don't sort because the
        // caller relies on positional correspondence with the request.
        Ok(rows.into_iter().map(Event::from).collect())
    }

    async fn list(
        &self,
        filter: ListEventsFilter,
        page_size: i32,
        page_token: PageToken,
    ) -> Result<ListEventsPage, HeadlinesError> {
        let limit = clamp_page_size(page_size);

        let cursor = if page_token.is_empty() {
            None
        } else {
            Some(decode_cursor(page_token.as_str())?)
        };

        let mut conn = self.db.get().await.map_err(HeadlinesError::Internal)?;

        // Build the WHERE-clause progressively. Each filter slot binds in a
        // fixed positional order so the query string can be assembled
        // statically and still vary by which filters are present.
        let mut clauses: Vec<String> = vec!["1 = 1".into()];
        let mut next_param: usize = 1;

        let user_param = filter.user_id.map(|_| {
            let n = next_param;
            next_param += 1;
            clauses.push(format!("user_id = ${n}"));
            n
        });
        let article_param = filter.article_id.map(|_| {
            let n = next_param;
            next_param += 1;
            clauses.push(format!("article_id = ${n}"));
            n
        });
        let types_param = if !filter.types.is_empty() {
            let n = next_param;
            next_param += 1;
            clauses.push(format!("type = ANY(${n})"));
            Some(n)
        } else {
            None
        };
        let after_param = filter.received_after.map(|_| {
            let n = next_param;
            next_param += 1;
            clauses.push(format!("received_at >= ${n}"));
            n
        });
        let before_param = filter.received_before.map(|_| {
            let n = next_param;
            next_param += 1;
            clauses.push(format!("received_at < ${n}"));
            n
        });
        let cursor_received_param = cursor.as_ref().map(|_| {
            let n = next_param;
            next_param += 1;
            n
        });
        let cursor_id_param = cursor.as_ref().map(|_| {
            let n = next_param;
            next_param += 1;
            n
        });
        if let (Some(rp), Some(ip)) = (cursor_received_param, cursor_id_param) {
            clauses.push(format!("(received_at, id) > (${rp}, ${ip})"));
        }
        let limit_param = next_param;
        let where_clause = clauses.join(" AND ");
        // Alias `type` to `type_` so the `QueryableByName` row shape — which
        // can't use the SQL keyword `type` as a struct field — finds the
        // column by name.
        let sql = format!(
            "SELECT id, user_id, article_id, type AS type_, occurred_at, received_at, \
                    surface, properties \
             FROM events \
             WHERE {where_clause} \
             ORDER BY received_at ASC, id ASC \
             LIMIT ${limit_param}"
        );

        let plus_one: i64 = (limit as i64) + 1;
        let mut q = diesel::sql_query(&sql).into_boxed::<diesel::pg::Pg>();
        if user_param.is_some() {
            q = q.bind::<SqlUuid, _>(filter.user_id.unwrap());
        }
        if article_param.is_some() {
            q = q.bind::<SqlUuid, _>(filter.article_id.unwrap());
        }
        if types_param.is_some() {
            let type_strs: Vec<String> = filter.types.iter().map(|t| t.0.clone()).collect();
            q = q.bind::<diesel::sql_types::Array<Text>, _>(type_strs);
        }
        if after_param.is_some() {
            q = q.bind::<Timestamptz, _>(filter.received_after.unwrap());
        }
        if before_param.is_some() {
            q = q.bind::<Timestamptz, _>(filter.received_before.unwrap());
        }
        if let Some((dt, id)) = cursor {
            q = q.bind::<Timestamptz, _>(dt);
            q = q.bind::<SqlUuid, _>(id);
        }
        q = q.bind::<diesel::sql_types::BigInt, _>(plus_one);

        let rows: Vec<EventRow> = q
            .load(&mut conn)
            .await
            .map_err(|e| HeadlinesError::Internal(anyhow::anyhow!("list events: {e}")))?;

        let mut rows = rows;
        let has_more = rows.len() as i32 > limit;
        if has_more {
            rows.truncate(limit as usize);
        }
        let last = rows.last().map(|r| (r.received_at, r.id));
        let items: Vec<Event> = rows.into_iter().map(Event::from).collect();
        let next_page_token = if has_more {
            match last {
                Some((dt, id)) => encode_cursor(&dt, id),
                None => PageToken::empty(),
            }
        } else {
            PageToken::empty()
        };

        Ok(ListEventsPage {
            items,
            next_page_token,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cursor_round_trips_through_base64_json() {
        // Arrange
        let now = Utc::now();
        let id = Uuid::now_v7();

        // Act
        let token = encode_cursor(&now, id);
        let (dt, decoded_id) = decode_cursor(token.as_str()).unwrap();

        // Assert
        assert_eq!(decoded_id, id);
        assert_eq!(dt.timestamp(), now.timestamp());
    }

    #[test]
    fn decode_cursor_rejects_non_base64() {
        // Arrange
        let raw = "not!base64";

        // Act
        let res = decode_cursor(raw);

        // Assert
        assert!(matches!(res, Err(HeadlinesError::InvalidCursor { .. })));
    }

    #[test]
    fn decode_cursor_rejects_non_json_payload() {
        // Arrange — valid base64 but not the expected JSON shape.
        let raw = B64URL.encode(b"hello world");

        // Act
        let res = decode_cursor(&raw);

        // Assert
        assert!(matches!(res, Err(HeadlinesError::InvalidCursor { .. })));
    }

    #[test]
    fn clamp_page_size_clamps_into_range() {
        // Arrange / Act / Assert
        assert_eq!(clamp_page_size(0), DEFAULT_PAGE_SIZE);
        assert_eq!(clamp_page_size(-1), DEFAULT_PAGE_SIZE);
        assert_eq!(clamp_page_size(1), 1);
        assert_eq!(clamp_page_size(MAX_PAGE_SIZE), MAX_PAGE_SIZE);
        assert_eq!(clamp_page_size(MAX_PAGE_SIZE + 1), MAX_PAGE_SIZE);
    }
}
